inherit_from:
  - '.rubocop_core.yml'

# Put your project-specifc Rubocop config here

Style/IndentationWidth:
  Enabled: false

Metrics/LineLength:
  Enabled: false

Style/EmptyLinesAroundBlockBody:
  Exclude:
    - 'spec/**/*.rb'
